version: "3.8"

services:
  go-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_GO_API_URL: "http://go-backend:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # This anonymous volume preserves container's node_modules
    depends_on:
      - go-backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"